[package]
name = "boot-image"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
fatfs = "0.3.5"
gpt = "3.0.0"
tempfile = "3.3.0"

[features]
aarch64 = []
x86_64 = []